# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
on: push
env:
  GRAALVM_HOME: /opt/graalvm-ce-java11-20.0.0
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: oracle/graalvm-ce:20.0.0-java11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: install native-image
      run: gu install native-image

    - name: install clojure
      run: /bin/bash -c "$(curl -fsSL https://download.clojure.org/install/linux-install-1.10.1.561.sh)"

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build mj executable
      run: clojure -m makejack.main build
