# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
on: push
  # push:
  #   branches:
  #     - 'master'

name: Build site

jobs:
  build-site:
    name: Build Site
    runs-on: macos-latest
    steps:
    - name: Install hugo
      run: brew install hugo
    - name: Install clojure
      run: brew install clojure
    - name: Install babashka
      run: brew install borkdude/brew/babashka
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: build makejack script
      run: |
        bin/bootstrap-script --verbose
    - name: build site
      run: |
        npm install -g postcss-cli
        npm install -g autoprefixer
        #;git submodule update --init --recursive
        target/mj-script build-site
        cd public
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        cd public
        git status
        [[ -z $(git status -s) ]] || git commit -m "Build site" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: public
        github_token: ${{ secrets.GITHUB_TOKEN }}
