# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
on: [push, pull_request]
name: Run tests

jobs:
  tests:
    name: Tests
    runs-on: macos-latest
    strategy:
      matrix:
        cli-version: ["clojure", "clojure/tools/clojure@1.10.1.697"]
    steps:
    - name: Install clojure
      run: brew install ${{ matrix.cli-version }}
    - name: Install babashka
      run: brew install borkdude/brew/babashka
    - name: Install clj-kondo
      run: brew install borkdude/brew/clj-kondo
    - uses: actions/checkout@v2
    - name: build
      run: |
        bin/bootstrap-script --debug --verbose
    - name: tests
      run: |
        bb ./cli/target/mj-script test
    - name: lint
      run: |
        bb ./cli/target/mj-script lint
    - name: fmt
      run: |
        bb ./cli/target/mj-script fmt
