# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
on: [push, pull_request]
name: Run tests

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        cli-version: ["clojure", "clojure/tools/clojure@1.10.1.681"]
    steps:
    - name: Install clojure
      run: brew install ${{ matrix.cli-version }}
    - name: Install babashka
      run: brew install borkdude/brew/babashka
    - uses: actions/checkout@v2
    - name: build
      run: |
        bin/bootstrap-script --debug --verbose
    - name: tests
      run: |
        bb ./mj-script test
        cd tools
        bb ../mj-script test
    - name: lint
      run: |
        bb ./mj-script lint
    - name: fmt
      run: |
        bb ./mj-script fmt
